branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: eb-washerportal
  branch: null
  default_platform: Ruby 2.5 (Puma)
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  workspace_type: Application
