branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: eb-washerportal
  branch: master
  default_ec2_keyname: loopie
  default_platform: Ruby 2.5 (Puma)
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: washerportal
  sc: git
  workspace_type: Application
